# -*- coding: utf-8 -*-
"""PRODIGY_DS_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u_TJjRv4ztUDdkGCLpvSEK5ym25BFaFp
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the Titanic dataset from GitHub
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
titanic_df = pd.read_csv(url)

# Data Cleaning
# Check for missing values
print(titanic_df.isnull().sum())

# Drop rows with missing values
titanic_df.dropna(inplace=True)

# Check for duplicates
print(titanic_df.duplicated().sum())

# Data Exploration
# Summary statistics
print(titanic_df.describe())

# Explore categorical variables
print(titanic_df['Survived'].value_counts())
print(titanic_df['Sex'].value_counts())
print(titanic_df['Embarked'].value_counts())

# Explore numerical variables
print(titanic_df['Age'].describe())
print(titanic_df['Fare'].describe())

# Visualize relationships between variables
# Histogram of Age
plt.hist(titanic_df['Age'], bins=20)
plt.title('Distribution of Age')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()

# Histogram of Fare
plt.hist(titanic_df['Fare'], bins=20)
plt.title('Distribution of Fare')
plt.xlabel('Fare')
plt.ylabel('Frequency')
plt.show()

# Bar chart of Survived by Sex
sns.countplot(x='Sex', hue='Survived', data=titanic_df)
plt.title('Survival by Sex')
plt.xlabel('Sex')
plt.ylabel('Count')
plt.show()

# Bar chart of Survived by Embarked
sns.countplot(x='Embarked', hue='Survived', data=titanic_df)
plt.title('Survival by Embarked')
plt.xlabel('Embarked')
plt.ylabel('Count')
plt.show()

# Select only numerical columns
numerical_cols = titanic_df.select_dtypes(include=[np.number]).columns

# Correlation matrix
corr_matrix = titanic_df[numerical_cols].corr()
print(corr_matrix)

# Heatmap of correlation matrix
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', square=True)
plt.title('Correlation Matrix')
plt.show()

